// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {store} from '../models';
import {llm} from '../models';

export function AbandonSession():Promise<void>;

export function CheckModel():Promise<string>;

export function DeleteSession(arg1:string):Promise<void>;

export function FinishSession(arg1:domain.Snapshot):Promise<domain.Review>;

export function GetAreas(arg1:domain.Mode):Promise<Array<domain.AreaInfo>>;

export function GetProfile(arg1:domain.Mode):Promise<domain.Profile>;

export function GetSettings():Promise<store.Settings>;

export function GetStatus():Promise<domain.Status>;

export function GetStoreRoot():Promise<string>;

export function ListModels():Promise<Array<llm.ModelInfo>>;

export function ListSessions():Promise<Array<domain.Session>>;

export function PauseSession():Promise<void>;

export function ResumeSession():Promise<void>;

export function SaveSettings(arg1:store.Settings):Promise<void>;

export function StartSession(arg1:domain.SessionSpec):Promise<domain.Problem>;

export function UpdateSnapshot(arg1:domain.Snapshot):Promise<void>;
