// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbandonSession() {
  return window['go']['main']['App']['AbandonSession']();
}

export function CheckModel() {
  return window['go']['main']['App']['CheckModel']();
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function FinishSession(arg1) {
  return window['go']['main']['App']['FinishSession'](arg1);
}

export function GetAreas(arg1) {
  return window['go']['main']['App']['GetAreas'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetStoreRoot() {
  return window['go']['main']['App']['GetStoreRoot']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function PauseSession() {
  return window['go']['main']['App']['PauseSession']();
}

export function ResumeSession() {
  return window['go']['main']['App']['ResumeSession']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartSession(arg1) {
  return window['go']['main']['App']['StartSession'](arg1);
}

export function UpdateSnapshot(arg1) {
  return window['go']['main']['App']['UpdateSnapshot'](arg1);
}
